spring.datasource.url: jdbc:postgresql://localhost:5431/db-chat
spring.datasource.username: user 
spring.datasource.password: user 
spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.database: POSTGRESQL

#spring.jpa.show-sql: true
#validate
spring.jpa.hibernate.ddl_auto: validate
# spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# spring.jpa.hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
# #######
spring.jpa.generate-ddl: true
# #########
# spring.jpa.hibernate.default_schema: public
spring.sql.init.platform: postgres

#FLYWAY
spring.flyway.locations: classpath:/db/migration
spring.flyway.schemas: public
